apiVersion: v1
kind: Service
metadata:
  name: devops-app-svc
spec:
  type: ClusterIP   # BUG 3: Change to NodePort to expose outside the cluster

  selector:
    app: devops-backend   # BUG 1: doesn't match pod labels (app: devops-app)

  ports:
    - name: http
      port: 80
      # BUG 2: targetPort is missing â€” add targetPort: 5000
      # BUG 4: add nodePort: 30080 (only needed when type: NodePort)
